# Generated by Django 4.1.7 on 2023-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('emp', 'Employee'), ('cli', 'Client')], default='emp', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='users/photo-profiles/%Y/%m/%d'),
        ),
    ]
