# Generated by Django 4.1.7 on 2023-03-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='date_created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
